imt/imt/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('users/', include('users.urls', namespace="users")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imt/main/urls.py
from django.contrib import admin
from django.urls import path,include

from . import views

urlpatterns = [
    path('',views.HomeView,name='home'),
    path("imtPage/", views.ImtPage,name='imtPage'),
    path("counter/", views.CounterView,name='counter'),
    path('dishes/', views.ShowDishList.as_view(), name='dishes'),
    path('category/<slug:slug>/', views.CategoryView.as_view(), name='category'),
    path('post/<slug:slug>/', views.ShowPost.as_view(), name='post'),
    path("dietary/", views.DietaryList.as_view(),name='dietary'),
    path('diet/<slug:slug>/', views.ShowDiet.as_view(), name='diet'),
    path('category1/<slug:slug>/', views.CategoryView1.as_view(), name='category1'),
    path('search/',views.Search.as_view(),name='search'),
    path('addpost/', views.AddPost.as_view(), name='add_post'),
    path('adddiet/', views.AddDiet.as_view(), name='add_diet'),
    path('posts/<int:user_id>', views.Post.as_view(), name='posts'),
    path('menu/<int:user_id>', views.Menu.as_view(), name='menu'),

]

imt/users/urls.py
from django.urls import path,include
from . import views
from users.views import Register

app_name='users'

urlpatterns = [
    path('',include('django.contrib.auth.urls')),
    path('register/',Register.as_view(),name='register'),
    path('profile/<int:user_pk>', views.ProfileView.as_view(), name='profile'),
    path('profile_update/', views.profile, name='profile_update'),

]

imt/main/models.py
from django.db import models
from django.core.validators import MinValueValidator,MaxValueValidator
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.utils.text import slugify


class IMT(models.Model):
    weight=models.IntegerField(validators=[MaxValueValidator(250),MinValueValidator(35)])
    height=models.IntegerField(validators=[MaxValueValidator(230),MinValueValidator(120)])
    time_create=models.DateTimeField(auto_now_add=True)
    imt=models.PositiveIntegerField(null=True)

    def get_imt(self):
        self.imt=self.weight/((self.height/100)**2)
        return round(self.imt,2)
    

class Dish(models.Model):
    title=models.CharField(max_length=100)
    recipe=models.TextField(max_length=600)
    img=models.ImageField(upload_to="img/", default=None,
                              blank=True, null=True)
    slug=models.SlugField(unique=True)
    cat=models.ForeignKey('Category',on_delete=models.PROTECT)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, default=None)
    ingridients=models.TextField(max_length=600,default=None)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('post', kwargs={'slug': self.slug})
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Dish, self).save(*args, **kwargs)

class Category(models.Model):
    name=models.CharField(max_length=100)
    slug=models.SlugField(unique=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('category', kwargs={"slug": self.slug})


class Dietary(models.Model):
    title=models.CharField(max_length=100)
    description=models.TextField(max_length=600)
    slug=models.SlugField(unique=True)
    cat=models.ForeignKey('catDietary',on_delete=models.PROTECT)
    food=models.ManyToManyField('Dish')
    author = models.ForeignKey(User, on_delete=models.SET_NULL,  null=True, default=None)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('diet', kwargs={"slug": self.slug})
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Dietary, self).save(*args, **kwargs)



class catDietary(models.Model):
    name=models.CharField(max_length=100)
    slug=models.SlugField(unique=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('category1', kwargs={"slug": self.slug})

imt/main/forms.py
from django import forms

from .models import IMT,Dish,Dietary

class CountForm(forms.Form):
    weight = forms.IntegerField(min_value=30, max_value=300)
    height = forms.IntegerField(min_value=100, max_value=200)
    

class PostForm(forms.ModelForm):
    class Meta:
        model=Dish
        exclude=['author']

class DietForm(forms.ModelForm):
    class Meta:
        model=Dietary
        exclude=['author']

imt/main/views.py
from django.urls import reverse, reverse_lazy

from users.models import Profile
from .forms import CountForm, PostForm, DietForm
from .models import IMT, Dish,Category,Dietary, catDietary
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DetailView,ListView,CreateView
from itertools import chain
from django.contrib.auth.models import User


class Search(ListView):
    template_name='main/search.html'
    context_object_name='dishes'


    def get_queryset(self): # новый
        query = self.request.GET.get('q')
        dishes = Dish.objects.filter(title__icontains=query)
        menu = Dietary.objects.filter(title__icontains=query)
        
        results = chain(menu,dishes)
        return results
    

    


def HomeView(request):
    return render(request,'main/home.html')
   
    

def ImtPage(request):
    i=IMT.objects.latest('time_create')
    menu=Dietary.objects.all().order_by('-id')
    highs=Dietary.objects.all().filter(cat__name='high').order_by('-id')[:3]
    midls=Dietary.objects.all().filter(cat__name='midl').order_by('-id')[:3]
    lows=Dietary.objects.all().filter(cat__name='low').order_by('-id')[:3]
    return render(request,'main\imt.html',{'i':i,'menu':menu,'lows':lows,'midls':midls,'highs':highs})



def CounterView(request):
    if request.method=='POST':
        form=CountForm(request.POST)
        if form.is_valid():
            f=IMT(
                weight=form.cleaned_data['weight'],
                height=form.cleaned_data['height'],
            )
            f.save()
            return redirect('imtPage')
        else:
            form.add_error(None, 'Ошибка добавления поста')
    form=CountForm()

    imts=IMT.objects.all()
    return render(request,'main\counter.html',{'imts':imts,'form':form})


class ShowDishList(ListView):
    model = Dish
    template_name = 'main/dish_list.html'
    context_object_name = 'dishes'



class CategoryView(ListView):
    model = Dish
    template_name = 'main/category.html'
    context_object_name = 'dish_category'


    def get_queryset(self):
        self.category = Category.objects.get(slug=self.kwargs['slug'])
        queryset = Dish.objects.all().filter(cat__slug=self.category.slug)
        return queryset
    

class ShowPost(DetailView):
    model=Dish
    template_name='main/dish.html'
    context_object_name = 'post'
    

class DietaryList(ListView):
    model = Dietary
    template_name = 'main/dietary_list.html'
    context_object_name = 'dietaries'
    paginate_by=3

class ShowDiet(DetailView):
    model=Dietary
    template_name='main/diet.html'
    context_object_name = 'diet'




class CategoryView1(ListView):
    model = Dietary
    template_name = 'main/category1.html'
    context_object_name = 'diet_category'
    category=None
    paginate_by=3


    def get_queryset(self):
        self.category = catDietary.objects.get(slug=self.kwargs['slug'])
        queryset = Dietary.objects.all().filter(cat__slug=self.category.slug)
        return queryset



class AddPost(CreateView):
    form_class = PostForm
    template_name = 'main/addpost.html'

    def form_valid(self, form):
        w = form.save(commit=False)
        w.author = self.request.user
        return super().form_valid(form)


class AddDiet(CreateView):
    form_class = DietForm
    template_name = 'main/adddiet.html'

    def form_valid(self, form):
        w = form.save(commit=False)
        w.author = self.request.user
        return super().form_valid(form)

class Post(ListView):
    model=Dish
    context_object_name='dishes'
    template_name='main/post_list'

    def get_queryset(self):
        return Dish.objects.filter(author_id=self.kwargs['user_id'])
    
class Menu(ListView):
    model=Dietary
    context_object_name='dietaries'
    

    def get_queryset(self):
        return Dietary.objects.filter(author_id=self.kwargs['user_id'])

imt/main/templates/main/adddiet.html
{% extends 'base.html' %}

{% block content %}
<h1>ADD DIET</h1>
<div class='form'>
<form class='form-post' action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Отправить</button></p>
</form>
</div>
{% endblock %}

imt/main/templates/main/addpost.html
{% extends 'base.html' %}

{% block content %}
<h1>ADD DISH</h1>
<div class='form'>
<form class='form-post' action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Отправить</button></p>
</form>
</div>
{% endblock %}

imt/main/templates/main/category.html
{% extends "base.html" %}

{% block content %}
{% for dish in dish_category %}
<div class="dish">
<a href="{{dish.get_absolute_url}}"><div class='title1'>{{dish.title}}</div></a>
<img src="{{dish.img.url}}" class="imgList" alt="" >
</div>
{% endfor %}
{% endblock content %}

imt/main/templates/main/category1.html
{% extends "base.html" %}

{% block content %}
<div class="all">
{% for diet in diet_category %}

<div class="diet">
    <div class='titled'><a href="{{diet.get_absolute_url}}">{{diet.title}}</a></div>
    
    <div class="fl">
        {% for f in diet.food.all %}
            <div >
            <div class='title2'><a href="{{f.get_absolute_url}}">{{f.title}}</a></div>
            <img src="{{f.img.url}}" class="imgf" alt="" >
        </div>
        {% endfor %}
    </div>
</div>

{% endfor %}
</div>

<div class='footer'>
    {% for page_number in page_obj.paginator.get_elided_page_range %}
        {% if page_number == page_obj.paginator.ELLIPSIS %}
            {{page_number}}
        {% else %}
            <a href="?page={{ page_number }}"class="{% if page_number == page_obj.number %}current{% endif %}">
                {{page_number}}
            </a>
        {% endif %}
    {% endfor %}
    </div>
    </div>

{% endblock content %}

imt/main/templates/main/counter.html
{% extends 'base.html' %}

{% block content %}
<h1>IMT</h1>
<div class='form'>
<form class='form-post' action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Отправить</button></p>
</form>
</div>
{% endblock %}

imt/main/templates/main/diet.html
{% extends "base.html" %}

{% block content %}

<div class='flex'>
    <div class="post1">
        <div class="posttitle">{{diet.title}}</div>
        
        <div class="fl">
        {% for f in diet.food.all %}
            <div class='o'>
            <div class='title2'><a href="{{f.get_absolute_url}}">{{f.title}}</a></div>
            <img src="{{f.img.url}}" class="imgf" alt="" >
        </div> 
        {% endfor %}
    </div>

        
    <a href="{{diet.cat.get_absolute_url}}"><div class='dietc'>{{diet.cat}}</div></a>
    <a href="{% url 'users:profile' user_pk=diet.author.pk %}"><div class='dieta'>{{diet.author}}</div></a>
    
    </div>
</div>

{% endblock content %}

imt/main/templates/main/dietary_list.html
{% extends "base.html" %}

{% block content %}

<div class="wrapper">
{% for diet in dietaries %}
<div class="all">

<div class="diet">
    <div class='titled'><a href="{{diet.get_absolute_url}}">{{diet.title}}</a></div>
    
    <div class="fl">
        {% for f in diet.food.all %}
            <div >
            <div class='title2'><a href="{{f.get_absolute_url}}">{{f.title}}</a></div>
            <img src="{{f.img.url}}" class="imgf" alt="" >
        </div>
        {% endfor %}
    </div>
    
</div>
</div>
{% endfor %}


<div class='footer'>
{% for page_number in page_obj.paginator.get_elided_page_range %}
    {% if page_number == page_obj.paginator.ELLIPSIS %}
        {{page_number}}
    {% else %}
        <a href="?page={{ page_number }}"class="{% if page_number == page_obj.number %}current{% endif %}">
            {{page_number}}
        </a>
    {% endif %}
{% endfor %}
</div>
</div>



{% endblock content %}

imt/main/templates/main/dish.html
{% extends "base.html" %}
{% block content %}
<div class='flex'>
  <div class="post">
    <div class="posttitle">{{ post.title }}</div>
    


    <div class="photo">
      
      <div class="posti">
        
    {% if post.img %}
  <img src="{{ post.img.url }}" class="imgList" alt="Image of {{ post.title }}">
{% else %}
  <p>No image available</p>
{% endif %}
      </div>
      
      <div class="ingr">{{ post.ingridients }}</div>
    </div>

    <div class="postr">{{ post.recipe }}</div>

    <div class='p'>
      <a href="{{ post.cat.get_absolute_url }}"><div class='postc'>{{ post.cat }}</div></a>
      <a href="{% url 'users:profile' user_pk=post.author.pk  %}"><div class='posta'>{{ post.author }}</div></a>
    </div>
  </div>
</div>
{% endblock content %}

imt/main/templates/main/dish_list.html
{% extends "base.html" %}

{% block content %}
<div class="dish-wrapper">
    {% for dish in dishes %}
        {% if forloop.first or forloop.counter0|divisibleby:3 %}
        <div class="dish-row">
        {% endif %}

        <div class="dish-item">
            <a href="{{ dish.get_absolute_url }}"><div class='title1'>{{ dish.title }}</div></a>
            {% if dish.img %}
            <img src="{{ dish.img.url }}" class="imgList" alt="">
            {% endif %}
        </div>

        {% if forloop.counter|divisibleby:3 or forloop.last %}
        </div>
        {% endif %}
    {% endfor %}
</div>
{% endblock content %}

imt/main/templates/main/home.html
{% extends "base.html" %}
{% load imt_tags %}

{% block content %}

<div class="s">
<div class='search'>
<form  action="{% url 'search' %}" method='get'>
    <input type='text' name='q' placeholder="search">
    <button type='submit'>Search</button>
</form>
</div>
</div>


<div class='categories'>

<div class="cat_d2">
<p>CATEGORIES OF FOOD</p>
{%get_categories%}
</div>

<div class='cat_d'>
<p>CATEGORIES OF DIET</p>
{%get_categories1%}
</div>
</div>

{% endblock content %}

imt/main/templates/main/imt.html
{% extends "base.html" %}

{% block content %}
<div class="imtt">{{i.get_imt}}</div>

<div class='wrap3'></div>
{% for low in lows %}
{% if low.cat.name == 'low' and i.get_imt > 30%}
<div class='title3'><a href="{{low.get_absolute_url}}">{{low.title}}</a></div>
{% endif %}
{% endfor %}

{% for midl in midls %}
{% if midl.cat.name == 'midl' and i.get_imt >= 18 and i.get_imt < 30%}
<div class='title3'><a href="{{midl.get_absolute_url}}">{{midl.title}}</a></div>
{% endif %}
{% endfor %}

{% for high in highs %}
{% if high.cat.name == 'high' and i.get_imt < 18 %}
<div class='title3'><a href="{{high.get_absolute_url}}">{{high.title}}</a></div>
{% endif %}
{% endfor %}



{%if i.get_imt < 18 %}
<div class='title3'><a href ="http://127.0.0.1:8000/category1/high/" >VIEW ALL IN THAT CALORIES</a></div>
{% elif i.get_imt >= 18 and i.get_imt < 30%}
<div class='title3'><a href ="http://127.0.0.1:8000/category1/midl/" >VIEW ALL IN THAT CALORIES</a></div>
{% elif i.get_imt > 30%}
<div class='title3'><a href ="http://127.0.0.1:8000/category1/low/" >VIEW ALL IN THAT CALORIES</a></div>
{% endif %}

<div class='title3'><a href ="http://127.0.0.1:8000/dietary/" >VIEW ALL DIETARIES</a></div>
</div>

{% endblock content %}

imt/main/templates/main/list_category.html
{% for cat in cats %}
     <div class="cat">
     <p><li class='cat2'><a href="{{ cat.get_absolute_url }}">{{cat.name}}</a></li></p>
     
 </div>
     
{% endfor %}

imt/main/templates/main/post_list.html
LLLLL

imt/main/templates/main/search.html
{% extends "base.html" %}

{% block content %}
<div class='wrapper'>
    <div class="all">
    {% for post in dishes %}
    <div class="diet">
        <a href="{{post.get_absolute_url}}"><div class='posttitle'>{{post.title}}</div></a>
        {% if post.img %}
        <img src="{{post.img.url}}" class="imgListt" alt="" >
        {% endif %}
        
        <div class="fl">
        {% for f in post.food.all %}
            <div class='o'>
            <div class='title2'><a href="{{f.get_absolute_url}}">{{f.title}}</a></div>
            <img src="{{f.img.url}}" class="imgff" alt="" >
        </div> 
        {% endfor %}
    </div>
    </div>
</div>
    {% endfor %}
</div>

{% endblock content %}